/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;
import java.util.Random; // importando biblioteca randomica

/**
 *
 * @author juant
 */
public class GenioAdivinha extends javax.swing.JFrame {

    /**
     * Creates new form GenioAdivinha
     */
    public GenioAdivinha() {
        initComponents();
        
        // Frase inicial sendo inserida no balão do gênio
        // Utilização de tags presente em html para caracteristicas de texto
        lblFraseGenio.setText("<html>Vou pensar em um valor entre <b>1 e 5</b>.<br> Tente Adivinhar<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGenioImage = new javax.swing.JLabel();
        btnPalpita = new javax.swing.JButton();
        spnPalpite = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblFraseGenio = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenioImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/pngenio.png"))); // NOI18N
        jPanel1.add(lblGenioImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        btnPalpita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPalpita.setText("Palpite");
        btnPalpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpitaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPalpita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        spnPalpite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(spnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 73, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Valor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblFraseGenio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFraseGenio.setText(".");
        jPanel1.add(lblFraseGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 80));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balon.png"))); // NOI18N
        jPanel1.add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpitaActionPerformed
        // TODO add your handling code here:
        
        // captura o palpite do usuario
        int palpiteUsuario = (int)spnPalpite.getValue();
        
        /* se o palpite digitado pelo usuario atender os requisitos do genio
            ele verifica se é realmente o numero que pensou */
        if(palpiteUsuario <= 5 && palpiteUsuario >= 1){
            Random rand = new Random(); 
            int numeroPensado = rand.nextInt(5) + 1; // número aleatório de 1 a 5

            /* Faz a verificação se o numero pensado é o mesmo do 
                palpite do usuario e retorna resposta */
            if (palpiteUsuario == numeroPensado) {
                lblFraseGenio.setText("<html><b>ACERTOU! Eu realmente pensei no valor " + numeroPensado + "</b></html>");
            } else {
                lblFraseGenio.setText("<html><b>ERROU! Eu pensei no valor " + numeroPensado + "</b></html>");
            }
        }
        // caso contrario, exibe mensagem de nova tentativa
        else{
            lblFraseGenio.setText("<html> Tente um valor no intervalo de <b>1 a 5</b> <html>");
        }
    }//GEN-LAST:event_btnPalpitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenioAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenioAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenioAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenioAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenioAdivinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpita;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblFraseGenio;
    private javax.swing.JLabel lblGenioImage;
    private javax.swing.JSpinner spnPalpite;
    // End of variables declaration//GEN-END:variables
}
