/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import javax.swing.JOptionPane;

/**
 *
 * @author juant
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        this.setLocationRelativeTo(null); // centraliza a janela na hora da execução
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormaPagamento = new javax.swing.ButtonGroup();
        lblFormaPagamento = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        btnImprimeRecibo = new javax.swing.JButton();
        rbPagamentoPix = new javax.swing.JRadioButton();
        rbPagamentoCartao = new javax.swing.JRadioButton();
        rbPagamentoDinheiro = new javax.swing.JRadioButton();
        lblSubtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormaPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFormaPagamento.setText("Forma de pagamento:");

        spnValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        btnImprimeRecibo.setText("Imprimir recibo");
        btnImprimeRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimeReciboActionPerformed(evt);
            }
        });

        bgFormaPagamento.add(rbPagamentoPix);
        rbPagamentoPix.setText("Pix");
        rbPagamentoPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagamentoPixActionPerformed(evt);
            }
        });

        bgFormaPagamento.add(rbPagamentoCartao);
        rbPagamentoCartao.setText("Cartao");
        rbPagamentoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagamentoCartaoActionPerformed(evt);
            }
        });

        bgFormaPagamento.add(rbPagamentoDinheiro);
        rbPagamentoDinheiro.setText("Dinheiro");
        rbPagamentoDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagamentoDinheiroActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addComponent(btnImprimeRecibo)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPagamentoPix)
                        .addGap(18, 18, 18)
                        .addComponent(rbPagamentoCartao)
                        .addGap(18, 18, 18)
                        .addComponent(rbPagamentoDinheiro))
                    .addComponent(lblFormaPagamento))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPagamentoPix)
                    .addComponent(rbPagamentoCartao)
                    .addComponent(rbPagamentoDinheiro))
                .addGap(18, 18, 18)
                .addComponent(btnImprimeRecibo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPagamentoPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagamentoPixActionPerformed
        // TODO add your handling code here:
        // exibe caracteristica do pagamento via pix
        JOptionPane.showMessageDialog(this, 
                "Em pagamentos via pix você recebe: \n2% de cashback (imediato)", 
                "Aviso", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rbPagamentoPixActionPerformed

    private void rbPagamentoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagamentoCartaoActionPerformed
        // TODO add your handling code here:
        // exibe caracteristica do pagamento via dinheiro
        JOptionPane.showMessageDialog(this, 
                "Pagamentos no cartão possui taxa de:: \n10% no valor total!!!", 
                "Aviso", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rbPagamentoCartaoActionPerformed

    private void btnImprimeReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimeReciboActionPerformed
        // TODO add your handling code here:
        
        double valorCompra = ((Number) spnValor.getValue()).doubleValue();
        
        // inicializa a interface como nulo
        Pagamento tipoPagamento = null;
       
        // verifica qual dos radiobutton está selecionado
        if (rbPagamentoPix.isSelected() && valorCompra > 0) {
            tipoPagamento = new PagamentoPix(valorCompra);
        } 
        else if (rbPagamentoCartao.isSelected() && valorCompra > 0) {
            tipoPagamento = new PagamentoCartao(valorCompra);
        }
        else if (rbPagamentoDinheiro.isSelected() && valorCompra > 0) {
            tipoPagamento = new PagamentoDinheiro(valorCompra);
        }
        else{
            /* Exibe mensagem de erro da forma de pagamento nao 
            selecionada ou valor menor ou igual a 0 */
            JOptionPane.showMessageDialog(this, 
                    " Forma de pagamento nao selecionada!\n Ou \n Valor invalido", 
                    "Erro ao gerar recibo", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
        // caso seja inicializada a interface acessa os metodos do objeto criado
        if (tipoPagamento != null){
            tipoPagamento.calcularTotal();
            tipoPagamento.imprimirRecibo();
        }

        
    }//GEN-LAST:event_btnImprimeReciboActionPerformed

    private void rbPagamentoDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagamentoDinheiroActionPerformed
        // TODO add your handling code here:
        // exibe caracteristica do pagamento via dinheiro
        JOptionPane.showMessageDialog(this, 
                "Em pagamentos no dinheiro você recebe: \n10% de desconto", 
                "Aviso", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rbPagamentoDinheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFormaPagamento;
    private javax.swing.JButton btnImprimeRecibo;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JRadioButton rbPagamentoCartao;
    private javax.swing.JRadioButton rbPagamentoDinheiro;
    private javax.swing.JRadioButton rbPagamentoPix;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
